INSERT INTO ROLES(ID, name)
VALUES(NEXTVAL('ROLES_ID_SEQUENCE'), 'ROLE_ADMIN');


INSERT INTO SYSTEM_USERS(ID, name, EMAIL, PASSWORD)
VALUES(NEXTVAL('SYSTEM_USERS_ID_SEQUENCE'), 'ADMIN', 'ADMIN@MAIL.COM', 'ADMIN');


INSERT INTO SYSTEM_USERS_ROLES(SYSTEM_USER_ID, ROLE_ID)
SELECT U.LAST_VALUE,
       R.LAST_VALUE
FROM ROLES_ID_SEQUENCE R,
           SYSTEM_USERS_ID_SEQUENCE U;


INSERT INTO ROLES(ID, name)
VALUES(NEXTVAL('ROLES_ID_SEQUENCE'), 'ROLE_USER');


INSERT INTO SYSTEM_USERS_ROLES(SYSTEM_USER_ID, ROLE_ID)
SELECT U.LAST_VALUE,
       R.LAST_VALUE
FROM ROLES_ID_SEQUENCE R,
     SYSTEM_USERS_ID_SEQUENCE U;

INSERT INTO SYSTEM_USERS(ID, name, EMAIL, PASSWORD)
VALUES(NEXTVAL('SYSTEM_USERS_ID_SEQUENCE'), 'USER', 'USER@MAIL.COM', 'USER');

INSERT INTO SYSTEM_USERS_ROLES(SYSTEM_USER_ID, ROLE_ID)
SELECT U.LAST_VALUE,
       R.LAST_VALUE
FROM ROLES_ID_SEQUENCE R,
     SYSTEM_USERS_ID_SEQUENCE U;